In [4]:
import pandas as pd
import random

stu_data = pd.read_csv('./StudentsPerformance.csv')
stu_data = pd.DataFrame(stu_data)


print(stu_data.iloc[:,5].mean())  # math
print()
print(stu_data.iloc[:,6].mean())  # reading
print()
print(stu_data.iloc[:,7].mean())  # writing


# 전체 학생들의 math, reading, writing 점수의 평균을 구하세요.

66.089

69.169

68.054

In [ ]:
#3. Group별 math, reading, writing 점수의 평균을 구하세요.

#   A 그룹의 평균
print('A 그룹의 평균')
a = stu_data['race/ethnicity'] == 'group A'
print(stu_data.loc[a,'math score':].mean())
print()

#   B 그룹의 평균
print('B 그룹의 평균')
b = stu_data['race/ethnicity'] == 'group B'
print(stu_data.loc[b,'math score':].mean())
print()

#   C 그룹의 평균
print('C 그룹의 평균')
c = stu_data['race/ethnicity'] == 'group C'
print(stu_data.loc[c,'math score':].mean())
print()

#   D 그룹의 평균
print('D 그룹의 평균')
d = stu_data['race/ethnicity'] == 'group D'
print(stu_data.loc[d,'math score':].mean())
print()

#   E 그룹의 평균
print('E 그룹의 평균')
e = stu_data['race/ethnicity'] == 'group E'
print(stu_data.loc[e,'math score':].mean())
print()

A 그룹의 평균
math score       61.629213
reading score    64.674157
writing score    62.674157
dtype: float64

B 그룹의 평균
math score       63.452632
reading score    67.352632
writing score    65.600000
dtype: float64

C 그룹의 평균
math score       64.463950
reading score    69.103448
writing score    67.827586
dtype: float64

D 그룹의 평균
math score       67.362595
reading score    70.030534
writing score    70.145038
dtype: float64

E 그룹의 평균
math score       73.821429
reading score    73.028571
writing score    71.407143
dtype: float64

In [ ]:
# 4. Group C에 속하는 남자와 여자들 각각의 math, reading, writing 점수의 평균을 구하세요.

print('group C 여자의 평균')
c = stu_data['race/ethnicity'] == 'group C'
sex_female = stu_data['gender'] == 'female'
print(stu_data.loc[c & sex_female,'math score':].mean())
print()
print('group C 남자의 평균')
sex_male = stu_data['gender'] == 'male'
print(stu_data.loc[c & sex_male,'math score':].mean())

group C 여자의 평균
math score       62.033333
reading score    71.944444
writing score    71.777778
dtype: float64

group C 남자의 평균
math score       67.611511
reading score    65.424460
writing score    62.712230
dtype: float64

In [34]:
# 5. 남자들 중에서 수학 점수가 80점 이상인 학생들은 몇 명인가요?


more_80 = stu_data['math score'] > 80
sex = stu_data['gender'] == 'male'
male_count=stu_data.loc[more_80&sex]
print(len(male_count))

108

In [6]:
# 6. 시험 준비 과정을 완료 한 학생들만 남기고 모두 삭제하세요.


test_none = stu_data['test preparation course'] == 'none'
stu_data_test_none = stu_data[test_none]
stu_data.drop(stu_data_test_none.index)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [38]:
# 7. 6의 결과로 나온 학생들의 Listening score를 추가하세요
# - Hint. Random 함수를 사용해서 학생 수만큼 0~100점 사이의 랜덤한 점수를 추가해서 사용


deleted_stu_data=stu_data.drop(stu_data_test_none.index)

i = 0
for i in deleted_stu_data.index:
    deleted_stu_data.loc[i,'Listening'] = random.randint(0,100)

deleted_stu_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Listening
1,female,group C,some college,standard,completed,69,90,88,24.0
6,female,group B,some college,standard,completed,88,95,92,66.0
8,male,group D,high school,free/reduced,completed,64,64,67,60.0
13,male,group A,some college,standard,completed,78,72,70,20.0
18,male,group C,master's degree,free/reduced,completed,46,42,46,13.0
...,...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75,36.0
991,female,group B,some high school,standard,completed,65,82,78,92.0
995,female,group E,master's degree,standard,completed,88,99,95,44.0
997,female,group C,high school,free/reduced,completed,59,71,65,63.0
998,female,group D,some college,standard,completed,68,78,77,38.0